# Generated by Django 3.2.9 on 2021-11-27 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorizer', '0002_auto_20211124_2049'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dbcourseoffering',
            old_name='time',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='dbcourseoffering',
            name='days',
            field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dbcourseoffering',
            name='start_time',
            field=models.TimeField(default=datetime.time(1, 0)),
            preserve_default=False,
        ),
    ]
