# Generated by Django 3.2.9 on 2021-11-27 18:03

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorizer', '0003_auto_20211127_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcourseoffering',
            name='days',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday')], max_length=1), size=None),
        ),
    ]
