# Generated by Django 3.2.9 on 2021-11-25 03:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('majorizer', '0003_dbuser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dbuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='dbuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='dbuser',
            name='username',
        ),
        migrations.AddField(
            model_name='dbuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
