# Generated by Django 3.2.9 on 2021-11-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('majorizer', '0004_alter_dbcourseoffering_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dbcourseoffering',
            name='days',
            field=models.CharField(max_length=9),
        ),
    ]
